### ISSUE TITLE
Error on save w/o basic auth credentials

### ISSUE THREAD

**Issue by emsuiko** [codemonauts/craft-basicauth#1]
### Prerequisites
- installed basic auth plugin (d'uh)
- at least one set of credentials saved

### Steps to reproduce
- go to basic auth plugin settings
- delete all entries from the table (so that it's empty)
- save

### Expected behaviour
- all good, new settings saved, no credentials in the table anymore

### Current behaviour
- error: `Invalid argument supplied for foreach()`
- new settings aren't saved
![basic-auth-error](https://user-images.githubusercontent.com/4366030/120357021-45e7bd00-c305-11eb-877e-b16cd109048e.png)

**Comment by kringkaste** [comment]
Hi @emsuiko ! Thanks for your bug report. We have released 1.1.0 which will fix this bug.
